### ISSUE TITLE
MeshFaceData?

### ISSUE THREAD

**Issue by bmxam** [bcube-project/Bcube.jl#88]
Should we implement a MeshFaceData? If we want to perform a face integration involving a parameter/constant depending of the face domain, should we split the integral on each domain, or use a MeshFaceData?

**Comment by ghislainb** [comment]
Can you elaborate on what you are thinking about ? May be with a small example that shows how you want to use a `MeshFaceData`.
I wonder if the correct generalization woud not be a `DomainData` which can be set on a `CellDomain`/`FaceDomain`/...
