### ISSUE TITLE
Subdomain integration

### ISSUE THREAD

**Issue by bmxam** [bcube-project/Bcube.jl#89]
Enable volumic integration (i.e assembly) on CellDomain containing only a non-dense index of mesv cells. There is currently an error (raised by an assert).

This will be very usefull for multiphysics problem where the equations depend on the domain.

Currently, we can handle this case by writing the same equations everywhere and use MeshCellData. But this is quite bad for ergonomy and performance.

**Comment by bmxam** [comment]
Do you remember why https://github.com/bcube-project/Bcube.jl/blob/67f5fe6db20650887e6c0e858e86e51174f3cc43/src/mesh/domain.jl#L426 is necessary? It seems to me that we could just delete this here.

**Comment by bmxam** [comment]
A simple `Bcube.compute` seems to be working fine. I need to check with FESpaces (and test functions).

```julia-repl
using Bcube

n = 5
mesh = line_mesh(2 * n + 1; xmin = 0, xmax = 1)
sub1 = 1:2:(2 * n)
sub2 = 2:2:(2 * n)
dΩ = Measure(CellDomain(mesh), 1)
dΩ1 = Measure(CellDomain(mesh, sub1), 1)
dΩ2 = Measure(CellDomain(mesh, sub2), 1)
f = PhysicalFunction(x -> 1.0)
@show sum(Bcube.compute(∫(f)dΩ))
@show sum(Bcube.compute(∫(f)dΩ1))
@show sum(Bcube.compute(∫(f)dΩ2))
```

**Comment by ghislainb** [comment]
> Do you remember why
> 
> https://github.com/bcube-project/Bcube.jl/blob/67f5fe6db20650887e6c0e858e86e51174f3cc43/src/mesh/domain.jl#L426
> is necessary? It seems to me that we could just delete this here.

If you iterate over the `DomainIterator`, I think it's fine. The test was more a kind of reminder to not forget to think about the generalization of the concept of domains (for example : how to deal with the indexing relative to the mesh / domains / Multi-FESpace)
